// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbB6ZlIed0ZUZbDSg3kGMu9PPkIkS7TqU',
    appId: '1:682209281989:web:03dcff1fc22631623c2dac',
    messagingSenderId: '682209281989',
    projectId: 'hotelauth-ea8bc',
    authDomain: 'hotelauth-ea8bc.firebaseapp.com',
    storageBucket: 'hotelauth-ea8bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-aSl9wOo71qTCF7QVd5rbg0Fb1vB6Wis',
    appId: '1:682209281989:android:9a854bfc244116ea3c2dac',
    messagingSenderId: '682209281989',
    projectId: 'hotelauth-ea8bc',
    storageBucket: 'hotelauth-ea8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdTA1Gf8UWXnJ7uj4eUvusK4nvS2cjW5w',
    appId: '1:682209281989:ios:c6caaf93f952c0913c2dac',
    messagingSenderId: '682209281989',
    projectId: 'hotelauth-ea8bc',
    storageBucket: 'hotelauth-ea8bc.appspot.com',
    iosBundleId: 'com.example.hotelMng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdTA1Gf8UWXnJ7uj4eUvusK4nvS2cjW5w',
    appId: '1:682209281989:ios:c6caaf93f952c0913c2dac',
    messagingSenderId: '682209281989',
    projectId: 'hotelauth-ea8bc',
    storageBucket: 'hotelauth-ea8bc.appspot.com',
    iosBundleId: 'com.example.hotelMng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbB6ZlIed0ZUZbDSg3kGMu9PPkIkS7TqU',
    appId: '1:682209281989:web:db85f93ca4169b1d3c2dac',
    messagingSenderId: '682209281989',
    projectId: 'hotelauth-ea8bc',
    authDomain: 'hotelauth-ea8bc.firebaseapp.com',
    storageBucket: 'hotelauth-ea8bc.appspot.com',
  );
}
